#!/usr/bin/env node

var util = require("util");
var fs = require("fs");
var path = require("path");

var peg = require('pegjs');
var overrideAction = require('pegjs-override-action');

var inputFile = "resources/grammar.pegjs";
var exportVar = "var PEG";

/* generate ReVIEW parser */

var inputStream = fs.createReadStream(inputFile);
inputStream.on("error", function () {
	abort("Can't read from file \"" + inputFile + "\".");
});

var outputStream = process.stdout;
outputStream.on("error", function () {
	abort("Can't write to stdout.");
});

var template = {
	contents: function (ruleName) {
		var func = (function () {
			var processed = [c];
			if (cc) {
				if (Array.isArray(cc.content)) {
					cc.content.forEach(function (c) {
						processed.push(c);
					});
				} else {
					processed.push(cc.content);
				}
			}
			return {
				line: line(),
				column: column(),
				offset: offset(),
				endPos: peg$currPos,
				syntax: "RuleName",
				content: processed
			};
		}).toString().replace("RuleName", ruleName);
		// func.toString() で構文解析されるので eval で作らないといけない
		return eval("(" + func + ")");
	},
	content: function (ruleName) {
		var func = (function () {
			return {
				line: line(),
				column: column(),
				offset: offset(),
				endPos: peg$currPos,
				syntax: "RuleName",
				content: c
			};
		}).toString().replace("RuleName", ruleName);
		// func.toString() で構文解析されるので eval で作らないといけない
		return eval("(" + func + ")");
	},
	text: function (ruleName) {
		var func = (function () {
			return {
				line: line(),
				column: column(),
				offset: offset(),
				endPos: peg$currPos,
				syntax: "RuleName",
				text: text
			};
		}).toString().replace("RuleName", ruleName);
		// func.toString() で構文解析されるので eval で作らないといけない
		return eval("(" + func + ")");
	},
	repeat: function (times, obj) {
		var result = [];
		for (var i = 0; i < times; i++) {
			result.push(obj);
		}
		return result;
	}
};

var options =
{
	cache: true,
	output: "source",
	optimize: "speed",
	plugins: [overrideAction],
	overrideActionPlugin: {
		rules: {
			// 注意 Rule置き換えのfunctionは構文解析されて引数がgrammar中のラベル名に置き換えられます。
			Start: template.content("Start"),
			Chapters: template.contents("Chapters"),
			Chapter: function () {
				return {
					syntax: "Chapter",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					headline: headline,
					text: text
				};
			},
			Headline: function () {
				return {
					syntax: "Headline",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					level: level.length,
					label: label,
					caption: caption
				};
			},
			Contents: template.contents("Contents"),
			Content: template.repeat(7, template.content("Content")),
			Paragraph: template.content("Paragraph"),
			ParagraphSubs: template.contents("ParagraphSubs"),
			ParagraphSub: template.repeat(2, template.content("ParagraphSub")),
			ContentText: template.text("ContentText"),
			BlockElement: [
				function () {
					return {
						syntax: "BlockElement",
						line: line(),
						column: column(),
						offset: offset(),
						endPos: peg$currPos,
						symbol: symbol,
						args: args,
						content: contents
					};
				}, function () {
					return {
						syntax: "BlockElement",
						line: line(),
						column: column(),
						offset: offset(),
						endPos: peg$currPos,
						symbol: symbol,
						args: args,
						content: []
					};
				}
			],
			InlineElement: function () {
				return {
					syntax: "InlineElement",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					symbol: symbol,
					content: contents
				};
			},
			Column: function () {
				return {
					syntax: "Column",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					headline: headline,
					text: text
				};
			},
			ColumnHeadline: function () {
				return {
					syntax: "ColumnHeadline",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					level: level.length,
					caption: caption
				};
			},
			ColumnContents: template.contents("ColumnContents"),
			ColumnContent: template.repeat(7, template.content("ColumnContent")),
			ColumnTerminator: function () {
				return {
					syntax: "ColumnTerminator",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					level: level.length
				};
			},
			BracketArg: function () {
				return {
					syntax: "BracketArg",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					arg: arg
				};
			},
			BraceArg: function () {
				return {
					syntax: "BraceArg",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					arg: arg
				};
			},
			BlockElementContents: template.contents("BlockElementContents"),
			BlockElementContent: template.repeat(6, template.content("BlockElementContent")),
			BlockElementParagraph: template.content("Paragraph"),
			BlockElementParagraphSubs: template.contents("ParagraphSubs"),
			BlockElementParagraphSub: template.repeat(2, template.content("ParagraphSub")),
			BlockElementContentText: template.text("ContentText"),
			InlineElementContents: template.contents("InlineElementContents"),
			InlineElementContent: template.repeat(2, template.content("InlineElementContent")),
			InlineElementContentText: template.text("InlineElementContentText"),
			SinglelineContent: template.content("SinglelineContent"),
			ContentInlines: template.contents("ContentInlines"),
			ContentInline: template.repeat(2, template.content("ContentInline")),
			ContentInlineText: template.text("ContentInlineText"),
			Ulist: template.contents("Ulist"),
			UlistElement: function () {
				return {
					syntax: "UlistElement",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					level: level.length,
					text: text
				};
			},
			Olist: template.contents("Olist"),
			OlistElement: function () {
				return {
					syntax: "OlistElement",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					no: parseInt(n),
					text: text
				};
			},
			Dlist: template.contents("Dlist"),
			DlistElement: function () {
				return {
					syntax: "DlistElement",
					line: line(),
					column: column(),
					offset: offset(),
					endPos: peg$currPos,
					text: text,
					content: content
				};
			},
			DlistElementContent: template.content("DlistElementContent"),
			SinglelineComment: template.text("SinglelineComment")
		}
	}
};

readStream(inputStream, function (input) {
	try {
		var source = peg.buildParser(input, options);
	} catch (e) {
		if (e.line !== undefined && e.column !== undefined) {
			abort(e.line + ":" + e.column + ": " + e.message);
		} else {
			abort(e.message);
		}
	}

	outputStream.write(
		exportVar !== "" ? exportVar + " = " + source + ";\n" : source + "\n"
	);
	outputStream.write('if (typeof exports === "object") { exports.PEG = PEG; }' + "\n");
	if (outputStream !== process.stdout) {
		outputStream.end();
	}
});

/* from pegjs */
function exitSuccess() {
	process.exit(0);
}

function exitFailure() {
	process.exit(1);
}

function abort(message) {
	util.error(message);
	exitFailure();
}

function readStream(inputStream, callback) {
	var input = "";
	inputStream.on("data", function (data) {
		input += data;
	});
	inputStream.on("end", function () {
		callback(input);
	});
}
